name: npmpc

channels:
  - pytorch
  - defaults
  - conda-forge

dependencies:
  - python = 3.12
  - faiss-cpu  # Should install on gpu if available.
  - pip
  - pip:
    - do-mpc[full]
  - numpy
  - matplotlib
  - scikit-learn
  - tqdm
  - pyyaml