name: npmpc

channels:
  - pytorch
  - defaults
  - conda-forge

dependencies:
  - python = 3.12
  - faiss-gpu
  - pip
  - pip:
    - do-mpc[full]
  - numpy
  - matplotlib
  - gymnasium
  - mujoco
  - scikit-learn
  - tqdm
  - pyyaml
